version: "3.9"
services:
  nginx:
    image: nginx:1.23.3-alpine
    restart: unless-stopped
    volumes:
      - ${HTPASSWD_PATH}:/etc/apache2/.htpasswd
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  minio:
    image: minio/minio:RELEASE.2023-01-06T18-11-18Z.fips
    restart: unless-stopped
    working_dir: "/minio/storage"
    volumes:
      - ${MINIO_STORAGE_PATH}:/minio/storage
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: server /minio/storage --console-address ":9001"
  
  mlflow:
    image: "ghcr.io/mlflow/mlflow:v2.1.1"
    restart: unless-stopped
    depends_on: 
      - minio
    volumes: 
      - ${MLFLOW_STORAGE_PATH}:/mlflow
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
    command: mlflow server --backend-store-uri /mlflow --host 0.0.0.0 --port 5500 --default-artifact-root s3://${MLFLOW_S3_BUCKET_MAME}/

  tunnel:
    container_name: cloudflared-tunnel
    restart: unless-stopped
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
